const jobTitle = [
  {
    id: 1,
    title: "Front-End developer",
    company: "Wipro",
    location: "Pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Back-End developer",
    company: "Infosys",
    location: "Mumbai",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "1-Aug",
    img: "https://i0.wp.com/www.itvoice.in/wp-content/uploads/2017/09/Data-Infosys-Logo.jpg?ssl=1",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
  {
    id: 1,
    title: "Front-End developer",
    company: "wipro",
    location: "pune",
    status: "Apply",
    feedback: "lorem lorem",
    lastDate: "16-Aug",
    img: "https://1000logos.net/wp-content/uploads/2020/04/Logo-Wipro.jpg",
  },
];
export default jobTitle;
